name: subbeep
description: Managing and tracking all your subscriptions.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  hive_flutter: ^1.1.0
  lint_staged: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # linting
  flutter_lints: ^4.0.0
  husky: ^0.1.7

flutter:
  uses-material-design: true
